---
validate#postprocessing:
  _target_: Compose
  transforms:
  - _target_: Activationsd
    keys: pred
    softmax: true
  - _target_: Invertd
    keys:
    - pred
    - label
    transform: "@validate#preprocessing"
    orig_keys: image
    meta_key_postfix: meta_dict
    nearest_interp:
    - false
    - true
    to_tensor: true
  - _target_: AsDiscreted
    keys:
    - pred
    - label
    argmax:
    - true
    - false
    to_onehot: 3
  - _target_: CopyItemsd
    keys: "pred"
    times: 1
    names: "pred_save"
  - _target_: AsDiscreted
    keys:
    - pred_save
    argmax:
    - true
  - _target_: SaveImaged
    keys: pred_save
    meta_keys: pred_meta_dict
    output_dir: "@output_dir"
    resample: false
    squeeze_end_dims: true
validate#dataset:
    _target_: Dataset
    data: "@val_datalist"
    transform: "@validate#preprocessing"
validate#handlers:
- _target_: CheckpointLoader
  load_path: "$@ckpt_dir + '/model.pt'"
  load_dict:
    model: "@network"
- _target_: StatsHandler
  iteration_log: false
- _target_: MetricsSaver
  save_dir: "@output_dir"
  metrics:
  - val_mean_dice
  - val_acc
  metric_details:
  - val_mean_dice
  batch_transform: "$monai.handlers.from_engine(['image_meta_dict'])"
  summary_ops: "*"
evaluating:
- "$setattr(torch.backends.cudnn, 'benchmark', True)"
- "$@validate#evaluator.run()"
