---
image_key: image
transforms_infer:
  _target_: Compose
  transforms:
  - _target_: LoadImaged
    keys: "@image_key"
  - _target_: EnsureChannelFirstd
    keys: "@image_key"
  - _target_: Orientationd
    keys: "@image_key"
    axcodes: RAS
  - _target_: Spacingd
    keys: "@image_key"
    pixdim:
    - 1
    - 1
    - 1
    mode: bilinear
    align_corners:
    - true
  - _target_: CastToTyped
    keys: "@image_key"
    dtype: "$torch.float32"
  - _target_: NormalizeIntensityd
    keys: "@image_key"
    nonzero: true
    channel_wise: true
  - _target_: CastToTyped
    keys:
    - "@image_key"
    dtype:
    - "$torch.float32"
