image_key: image
transforms_infer:
  _target_: Compose
  transforms:
  - _target_: LoadImaged
    keys: "@image_key"
  - _target_: EnsureChannelFirstd
    keys: "@image_key"
  - _target_: Orientationd
    keys: "@image_key"
    axcodes: RAS
  - _target_: EnsureTyped
    keys: "@image_key"
    data_type: tensor
  - _target_: Spacingd
    keys: "@image_key"
    pixdim: null
    mode: bilinear
    align_corners: true
<<<<<<< HEAD
  - PLACEHOLDER_INTENSITY_NORMALIZATION