image_key: image
label_key: label
transforms_validate:
  _target_: Compose
  transforms:
  - _target_: LoadImaged
    keys:
    - '@image_key'
    - '@label_key'
  - _target_: EnsureChannelFirstd
    keys:
    - '@image_key'
    - '@label_key'
  - _target_: Orientationd
    axcodes: RAS
    keys:
    - '@image_key'
    - '@label_key'
  - _target_: Spacingd
    align_corners:
    - true
    - true
    keys:
    - '@image_key'
    - '@label_key'
    mode:
    - bilinear
    - nearest
    pixdim:
    - 1.0
    - 1.0
    - 1.0
  - _target_: CastToTyped
    dtype: $torch.float32
    keys: '@image_key'
  - _target_: NormalizeIntensityd
    channel_wise: true
    keys: '@image_key'
    nonzero: true
  - _target_: ScaleIntensityRanged
    a_max: 147.5986
    a_min: -45.8736
    b_max: 1.0
    b_min: 0.0
    clip: true
    keys: '@image_key'
  - _target_: CropForegroundd
    keys:
    - '@image_key'
    - '@label_key'
    source_key: '@image_key'
  - _target_: ScaleIntensityRanged
    a_max: 147.5986
    a_min: -45.8736
    b_max: 1.0
    b_min: 0.0
    clip: true
    keys: '@image_key'
  - _target_: CropForegroundd
    keys:
    - '@image_key'
    - '@label_key'
    source_key: '@image_key'
    _target_: ScaleIntensityRanged
    a_max: 147.5986
    a_min: -45.8736
    b_max: 1.0
    b_min: 0.0
    clip: true
    keys: '@image_key'
  - _target_: CropForegroundd
    keys:
    - '@image_key'
    - '@label_key'
    source_key: '@image_key'
  - _target_: ScaleIntensityRanged
    a_max: 147.5986
    a_min: -45.8736
    b_max: 1.0
    b_min: 0.0
    clip: true
    keys: '@image_key'
  - _target_: CropForegroundd
    keys:
    - '@image_key'
    - '@label_key'
    source_key: '@image_key'
  - _target_: CastToTyped
    dtype:
    - $torch.float32
    - $torch.uint8
    keys:
    - '@image_key'
    - '@label_key'
